spring:
  application:
    name: user-service

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: ${APP_VERSION:1.0.0}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    metadata-map:
      version: ${APP_VERSION:1.0.0}
  client:
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
  pattern:
    level: "%5p [${spring.application.name:},${eureka.instance.instance-id:unknown}]"